# Generated by Django 3.0.6 on 2020-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=250)),
                ('dni', models.IntegerField()),
                ('cuit', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Fisica',
                'verbose_name_plural': 'Fisicas',
            },
        ),
        migrations.CreateModel(
            name='Juridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('cuit', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'juridica',
                'verbose_name_plural': 'juridicas',
            },
        ),
    ]
